/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetTest"];
        put?: never;
        post: operations["CreateTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UpdateTest"];
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetUsersEndpoint"];
        put?: never;
        /** Creates a user account. */
        post: operations["CreateUserEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets a user by their id. */
        get: operations["GetUserByIdEndpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TestDto: {
            /** Format: typeid */
            id?: string;
            name?: string;
            description?: string | null;
            /** Format: date-time */
            queried?: string;
        };
        CreateTestRequest: {
            /** @description Optional id. */
            id?: string | null;
            /** @description Name of the test. */
            name: string;
            description?: string | null;
        };
        ProblemDetails: {
            /** @default https://www.rfc-editor.org/rfc/rfc7231#section-6.5.1 */
            type: string;
            /** @default One or more validation errors occurred. */
            title: string;
            /**
             * Format: int32
             * @default 400
             */
            status: number;
            /** @default /api/route */
            instance: string;
            /** @default 0HMPNHL0JHL76:00000001 */
            traceId: string;
            detail?: string | null;
            errors?: components["schemas"]["ProblemDetails_Error"][];
        };
        ProblemDetails_Error: {
            /** @default Error or field name */
            name: string;
            /** @default Error reason */
            reason: string;
            code?: string | null;
            severity?: string | null;
        };
        GetUsersResponseDto: {
            users?: components["schemas"]["UserDto"][];
            prevCursor?: string | null;
            nextCursor?: string | null;
        };
        /** @description Base type for any request that uses JsonPatch. */
        PatchRequestOfTest: {
            operations?: components["schemas"]["OperationOfTest"][];
        };
        OperationOfTest: components["schemas"]["Operation"] & Record<string, never>;
        Operation: components["schemas"]["OperationBase"] & {
            value?: unknown;
        };
        OperationBase: {
            operationType?: components["schemas"]["OperationType"];
            path?: string | null;
            op?: string | null;
            from?: string | null;
        };
        /** @enum {string} */
        OperationType: "Add" | "Remove" | "Replace" | "Move" | "Copy" | "Test" | "Invalid";
        /** @description Basic user account information. */
        UserDto: {
            /**
             * Format: typeid
             * @description The id of this resource.
             */
            id?: string;
            /**
             * Format: date-time
             * @description The timestamp when the user registered their account.
             */
            created?: string;
            /** @description The user's email address. */
            email?: string;
            /** @description The user's name shown in the UI. */
            name?: string;
            /** @description The version of this resource returned in the ETag header. */
            version?: string;
        };
        GetUsersRequest: {
            ifNoneMatch?: string | null;
        };
        /** @enum {string} */
        UserSearch: "Email" | "Name";
        /** @enum {string} */
        UserSort: "Created" | "CreatedDesc" | "Email" | "EmailDesc" | "Name" | "NameDesc";
        /** @description Request to get a user by their ID. */
        GetUserByIdRequest: {
            /** @description Optional ETag value for conditional requests. */
            ifNoneMatch?: string | null;
        };
        /** @description Request to create a new user account. */
        CreateUserRequest: {
            /**
             * Format: email
             * @description The user's email address, used as their login identifier.  Must be unique.
             */
            email: string;
            /** @description Name that will publicly identify the user. */
            displayName: string;
            /** @description The user's password. */
            password: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetTest: {
        parameters: {
            query?: {
                "api-version"?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestDto"][];
                };
            };
        };
    };
    CreateTest: {
        parameters: {
            query?: {
                "api-version"?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json; v=1.0": components["schemas"]["CreateTestRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    /** @example  */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestDto"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    UpdateTest: {
        parameters: {
            query?: {
                "api-version"?: string | null;
            };
            header?: {
                "if-Match"?: string | null;
            };
            path: {
                /** @description Id of the test resource. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json-patch+json; v=1.0": components["schemas"]["OperationOfTest"][];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    /** @example  */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetUsersEndpoint: {
        parameters: {
            query?: {
                "api-version"?: string | null;
                search?: components["schemas"]["UserSearch"] | null;
                term?: string | null;
                sort?: components["schemas"]["UserSort"];
                pageSize?: number;
                cursor?: string | null;
            };
            header?: {
                "if-None-Match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUsersResponseDto"];
                };
            };
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CreateUserEndpoint: {
        parameters: {
            query?: {
                "api-version"?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json; v=1.0": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description The user email or display name is already in use. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetUserByIdEndpoint: {
        parameters: {
            query?: {
                "api-version"?: string | null;
            };
            header?: {
                /** @description Optional ETag value for conditional requests. */
                "if-None-Match"?: string | null;
            };
            path: {
                /** @description The ID of the user to retrieve. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    ETag?: unknown;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
