services:
  web:
    container_name: hackathon-web
    build:
      context: .
      dockerfile: docker/integrated.Dockerfile
    environment:
      CONNECTIONSTRINGS__HACKATHONDB: Host=database;Port=5432;Username=postgres;Password=postgres;Database=hackathon
      ENABLESTARTUPMIGRATION: "true"
      LOG__ENABLECONSOLETEXTLOGGING: "true"
      LOG__ENABLEOPENTELEMETRYLOGGING: "true"
      LOG__OPENTELEMETRYLOGLEVEL: Verbose
      LOG__OPENTELEMETRYENDPOINT: http://seq:5341/ingest/otlp/v1/logs
      LOG__OPENTELEMETRYPROTOCOL: HttpProtobuf
    ports:
      - ${WEB_PORT:-5000}:8080
    depends_on:
      database:
        condition: service_healthy
      seq:
        condition: service_healthy

  database:
    extends:
      file: dependencies.yml
      service: database

  seq:
    extends:
      file: dependencies.yml
      service: seq

volumes:
  database:
    driver: local
  seq:
    driver: local
