services:
  proxy:
    container_name: hackathon-proxy
    image: nginx:1.28-alpine
    ports:
      - ${WEB_PORT:-5000}:80
    volumes:
      - ./docker/reverse-proxy.nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      api:
        condition: service_healthy

  spa:
    container_name: hackathon-spa
    build:
      context: .
      dockerfile: docker/spa.Dockerfile
    depends_on:
      api:
        condition: service_healthy

  api:
    container_name: hackathon-api
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    environment:
      CONNECTIONSTRINGS__HACKATHONDB: Host=database;Port=5432;Username=postgres;Password=postgres;Database=hackathon
      ENABLESTARTUPMIGRATION: "true"
      LOG__ENABLECONSOLETEXTLOGGING: "true"
      LOG__ENABLEOPENTELEMETRYLOGGING: "true"
      LOG__OPENTELEMETRYLOGLEVEL: Verbose
      LOG__OPENTELEMETRYENDPOINT: http://seq:5341/ingest/otlp/v1/logs
      LOG__OPENTELEMETRYPROTOCOL: HttpProtobuf
    depends_on:
      database:
        condition: service_healthy
      seq:
        condition: service_healthy

  database:
    extends:
      file: dependencies.yml
      service: database

  seq:
    extends:
      file: dependencies.yml
      service: seq

volumes:
  database:
    driver: local
  seq:
    driver: local
