services:
  web:
    container_name: hackathon-web
    build:
      context: .
      dockerfile: docker/integrated.Dockerfile
    env_file: dotnet-app.env
    ports:
      - ${WEB_PORT:-5000}:8080
    depends_on:
      database:
        condition: service_healthy

  database:
    extends:
      file: dependencies.yml
      service: database

volumes:
  database:
    driver: local
