services:
  web:
    container_name: hackathon-web
    build:
      context: .
      dockerfile: integrated.Dockerfile
    environment:
      CONNECTIONSTRINGS__HACKATHONDB: Host=database;Port=5432;Username=postgres;Password=postgres;Database=hackathon
      ENABLEDSTARTUPMIGRATION: "true"
      KESTREL__CERTIFICATES__DEFAULT__PATH: /certificates/${CERT_FILE}
      KESTREL__CERTIFICATES__DEFAULT__KEYPATH: /certificates/${KEY_FILE}
    ports:
      - ${WEB_PORT:-44300}:443
    volumes:
      - ${CERTIFICATES_PATH}:/certificates:ro
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: hackathon-database
    image: postgres:18beta1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hackathon
    ports:
      - ${DATABASE_PORT:-5432}:5432
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "PGUSER=postgres", "pg_isready"]
      start_period: 2s
      start_interval: 1s
      timeout: 5s
      retries: 15

volumes:
  database:
    driver: local
