services:
  web:
    container_name: hackathon-web
    build:
      context: .
      dockerfile: docker/integrated.Dockerfile
    environment:
      CONNECTIONSTRINGS__HACKATHONDB: Host=database;Port=5432;Username=postgres;Password=postgres;Database=hackathon
      ENABLESTARTUPMIGRATION: "true"
      KESTREL__CERTIFICATES__DEFAULT__PATH: /certificates/${CERT_FILE}
      KESTREL__CERTIFICATES__DEFAULT__KEYPATH: /certificates/${KEY_FILE}
    ports:
      - ${WEB_PORT:-44300}:443
    volumes:
      - ${CERTIFICATES_PATH}:/certificates:ro
    depends_on:
      database:
        condition: service_healthy
      seq:
        condition: service_healthy

  database:
    extends:
      file: dependencies.yml
      service: database

  seq:
    extends:
      file: dependencies.yml
      service: seq

volumes:
  database:
    driver: local
  seq:
    driver: local
