services:
  database:
    container_name: hackathon-database
    image: postgres:18beta1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hackathon
    ports:
      - ${DATABASE_PORT:-5432}:5432
    volumes:
      - database:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "PGUSER=postgres", "pg_isready"]
      start_period: 2s
      start_interval: 1s
      timeout: 5s
      retries: 15

  seq:
    container_name: hackathon-seq
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
      SEQ_API_CANONICALURI: https://localhost:${SEQ_PORT:-44301}
    ports:
      - ${SEQ_PORT:-44302}:443
    volumes:
      - seq:/data
      - ${CERTIFICATES_PATH}/${CERT_FILE}:/data/Certificates/443.pem:ro
      - ${CERTIFICATES_PATH}/${KEY_FILE}:/data/Certificates/443-key.pem:ro
    healthcheck:
        test: "/seqsvr/Client/seqcli node health -s http://localhost"
        start_period: 5s
        start_interval: 1s
        timeout: 5s
        retries: 15

volumes:
  database:
    driver: local
  seq:
    driver: local
