services:
  database:
    container_name: hackathon-database
    image: postgres:18beta1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hackathon
    ports:
      - ${DATABASE_PORT:-5432}:5432
    volumes:
      - database:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "PGUSER=postgres", "pg_isready"]
      start_period: 2s
      start_interval: 1s
      timeout: 5s
      retries: 15

  seq:
    container_name: hackathon-seq
    image: datalust/seq
    environment:
      ACCEPT_EULA: Y
      # password: admin
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: QNwxcXb5uVV9ZJma8mOK/ZbQzRTEDIrvupQHFnCkEYFzktF1UYWwa1DfjG7tyy4ceGbq3yrfqd2aUrli0EC/Izlyoh/AfJyuYZFD9WE/zAOw
      SEQ_API_CANONICALURI: http://localhost:${SEQ_PORT:-5341}
      SEQ_DIAGNOSTICS_INTERNALLOGGINGLEVEL: Warning
    ports:
      - ${SEQ_PORT:-5341}:80
    volumes:
      - seq:/data
    healthcheck:
        test: "/seqsvr/Client/seqcli node health -s http://localhost"
        start_period: 5s
        start_interval: 1s
        timeout: 5s
        retries: 15

volumes:
  database:
    driver: local
  seq:
    driver: local
