name: "Setup .Net"
description: "Set up .Net environment and restore packages"

runs:
  using: "composite"
  steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
        cache: true
        cache-dependency-path: "**/package-lock.json"

    - name: Restore NuGet packages
      run: dotnet restore --locked-mode
