name: "Hackathon SPA Task"
description: "Run a specified npm script for the Hackathon SPA project"

inputs:
  task:
    description: "npm script to run"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: "npm"

    - name: Restore dependencies
      run: npm ci
      shell: bash

    - name: Run npm script ${{ inputs.task }}
      run: npm run spa ${{ inputs.task }}
      shell: bash
